### ISSUE TITLE
Exception when upgrading to .NET 6 and ef core 6

### ISSUE THREAD

**Issue by jjxtra** [artiomchi/FlexLabs.Upsert#121]
Seeing this in my logs, looks like something broke with the .NET 6 or entity framework core 6 upgrade... I'm using nuget 6.0.2.

```
'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(Microsoft.EntityFrameworkCore.Metadata.IModel, System.Type)'.
   at FlexLabs.EntityFrameworkCore.Upsert.UpsertCommandBuilder`1..ctor(DbContext dbContext, ICollection`1 entities)
   at Microsoft.EntityFrameworkCore.UpsertExtensions.UpsertRange[TEntity](DbContext dbContext, IEnumerable`1 entities) in /_/src/FlexLabs.EntityFrameworkCore.Upsert/UpsertExtensions.cs:line 73
   at Microsoft.EntityFrameworkCore.UpsertExtensions.UpsertRange[TEntity](DbSet`1 dbSet, IEnumerable`1 entities) in /_/src/FlexLabs.EntityFrameworkCore.Upsert/UpsertExtensions.cs:line 130
```

**Comment by artiomchi** [comment]
Closing this as stale, this was likely fixed in a later release / no longer an issue in later releases
