### ISSUE TITLE
Exception when updating DateTime? Field

### ISSUE THREAD

**Issue by barrettg** [artiomchi/FlexLabs.Upsert#30]
First off, awesome library!

I'm trying to set my `UpdatedAt` timestamp using the `WhenMatched()` call.  Here is my code:
```
_context.Earnings.Upsert(new Earnings
{
    EmployeeId = employee.Id,
    ContributionGroupId = employee.CurrentEmploymentRecord.ContributionGroupId,
    JobPosition = employee.CurrentEmploymentRecord.JobPosition,
    PositionStatus = employee.CurrentEmploymentRecord.PositionStatus,
    PaymentReason = employee.CurrentEmploymentRecord.PaymentReason,
    ImportType = ImportType.MonthEnd,
    PostingDate = new DateTime(UploadEarnings.Year, UploadEarnings.Month, 1),
    GrossEarnings = earning.Amount.GetValueOrDefault(),
    CreatedAt = DateTime.Now,
})
.On(c => new { c.EmployeeId, c.ContributionGroupId, c.JobPosition, c.PositionStatus, c.PaymentReason, c.ImportType, c.PostingDate })
.WhenMatched(c => new Earnings
{
    UpdatedAt = DateTime.Now,
    GrossEarnings = earning.Amount.GetValueOrDefault()
})
.Run();
```
I receive the following exception when trying to set the `UpdatedAt` value: 

> The method or operation is not implemented.

If I omit `UpdatedAt` or try to set `CreatedAt` in `WhenMatched()` I do not get the exception.  The only difference between the two is that `CreatedAt` is a `DateTime` type and `UpdatedAt` is `DateTime?`.  Also, If I set `UpdatedAt` in the `Upsert()` call, I do not get the exception.  I'm a newbie, so maybe I'm missing something?

**Comment by barrettg** [comment]
I am on version 2.0.1 from NuGet as well as .Net Core 2.1. I took a look at #28 before posting this issue, but I wasn't sure if its the same problem.  I'm receiving the following stack trace in the exception:
```
   at FlexLabs.EntityFrameworkCore.Upsert.Internal.ExpressionHelpers.GetValue[TSource](Expression expression, LambdaExpression container, Boolean nested) in C:\projects\flexlabs-upsert\src\FlexLabs.EntityFrameworkCore.Upsert\Internal\ExpressionHelpers.cs:line 142
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.PrepareCommand[TEntity](IEntityType entityType, ICollection`1 entities, Expression`1 match, Expression`1 updater, Boolean noUpdate) in C:\projects\flexlabs-upsert\src\FlexLabs.EntityFrameworkCore.Upsert\Runners\RelationalUpsertCommandRunner.cs:line 103
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.Run[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Boolean noUpdate) in C:\projects\flexlabs-upsert\src\FlexLabs.EntityFrameworkCore.Upsert\Runners\RelationalUpsertCommandRunner.cs:line 217
   at FlexLabs.EntityFrameworkCore.Upsert.UpsertCommandBuilder`1.Run() in C:\projects\flexlabs-upsert\src\FlexLabs.EntityFrameworkCore.Upsert\UpsertCommandBuilder.cs:line 127
   at MyriadKRS.Pages.Start.EarningsModel.OnPostDatabaseAsync() in C:\GitHub\MyriadKRS\Pages\Start\Earnings.cshtml.cs:line 148
```

**Comment by artiomchi** [comment]
Ok, I've finally managed to trace the issue.. That's because your `UpdatedAt` property is nullable, and the value you're trying to assign it is not. Behind the scenes the expression generated by the framework is converting the value, which this library didn't handle yet.

I'm working on adding support for this, as well as reporting which expression failed to convert and instructions on how to handle this going forward

**Comment by artiomchi** [comment]
Right, I believe I got this working in the latest version, which is being deployed now: v2.0.2

Please let me know if the parch works, and if we can close this issue :)

**Comment by barrettg** [comment]
Sorry for the delay in my response...
You are correct, it is an issue of of the property being nullable.  If I declare a local variable of `DateTime? updatedAt = DateTime.Now;` and then use that value in `WhenMatched()` it works.  I have also tested version 2.0.2 and the issue is fixed when using the code unmodified from above.  Thanks!!!
