### ISSUE TITLE
When properties are defined in the model but not found on the entity to upsert, we get a NullReferenceException

### ISSUE THREAD

**Issue by SimonLuckenuik** [artiomchi/FlexLabs.Upsert#49]
Hi,
In our model, we inject properties that are not found on the entity we are upserting but that we want to populate automatically at execution time for Audit purposes.

We do something similar to this:
Our entity:
```
public class Synchronization
    {
        public string Id { get; set; }
        public DateTime LastSyncedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }

```

Our Upsert statement looks like this:
```
            await _dbContext.Synchronizations.Upsert(s).On(c => c.Id).WhenMatched((db, on) => new Synchronization
            {
                LastSyncedAt = on.LastSyncedAt
            }).RunAsync(ct);
```

In the Model configuration inside OnModelCreating:

```
        private void ModelSynchronization(ModelBuilder builder)
        {
            var model = builder.Entity<Synchronization>();
            model.ToTable("Synchronization");
            model.HasKey(s => s.Id);
            model.Property(c => c.Id).ValueGeneratedNever();
            model.ConfigureAuditProperties();
        }
```

Using this extension ConfigureAuditProperties method, we automatically update the audit columns (which are not found on the entity to persist):

```
public static class AuditExtensions
    {
        private static readonly string AuditCreatedAtPropertyName = "AuditCreatedAt";
        private static readonly string AuditLastUpdatedAtPropertyName = "AuditLastUpdatedAt";

        public static void ConfigureAuditProperties<T>(this EntityTypeBuilder<T> model) where T : class
        {
            model.Property<DateTime?>(AuditCreatedAtPropertyName);
            model.Property<DateTime?>(AuditLastUpdatedAtPropertyName);
        }

        public static void AuditEntityChanges(this BiDbContext context)
        {
            context.ChangeTracker.Entries()
                .Where(e => e.State == EntityState.Added || e.State == EntityState.Modified)
                .ForEach(e => AuditChangesFor(e));
        }

        private static void AuditChangesFor(EntityEntry tracked)
        {
            var now = DateTime.Now;

            var entityType = tracked.Context.Model.FindEntityType(tracked.Entity.GetType());
            if (entityType == null)
            {
                return;
            }

            var createdAtProperty = entityType.FindProperty(AuditCreatedAtPropertyName);
            var lastUpdatedAtProperty = entityType.FindProperty(AuditLastUpdatedAtPropertyName);

            if (tracked.State == EntityState.Added)
            {
                if (createdAtProperty != null)
                {
                    tracked.Property(AuditCreatedAtPropertyName).CurrentValue = now;
                }
                if (lastUpdatedAtProperty != null)
                {
                    tracked.Property(AuditLastUpdatedAtPropertyName).CurrentValue = now;
                }
            }
            else if (tracked.State == EntityState.Modified)
            {
                if (lastUpdatedAtProperty != null)
                {
                    tracked.Property(AuditLastUpdatedAtPropertyName).CurrentValue = now;
                }
            }
        }
    }
```

Executing the Upsert will generate the following exception, because the property from the model that is being searched doesn't actually exists on the entity type:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=FlexLabs.EntityFrameworkCore.Upsert
  StackTrace:
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.<>c__DisplayClass13_2`1.<PrepareCommand>b__7(IProperty p)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.<>c__DisplayClass13_0`1.<PrepareCommand>b__2(TEntity e)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.PrepareCommand[TEntity](IEntityType entityType, ICollection`1 entities, Expression`1 match, Expression`1 updater, Boolean noUpdate, Boolean useExpressionCompiler)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.<RunAsync>d__18`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SynchronizationRepository.<Upsert>d__2.MoveNext() in C:\src\SynchronizationRepository.cs:line 21
```
Code that throws:
```
 var newEntities = entities
                .Select(e => properties
                    .Select(p =>
                    {
                        var columnName = p.Relational().ColumnName;
                        var value = new ConstantValue(p.PropertyInfo.GetValue(e), p); // BUG: PropertyInfo is null here because it's not on the entity
                        return (columnName, value);
                    })
                    .ToArray() as ICollection<(string ColumnName, ConstantValue Value)>)
                .ToArray();
```

Thanks!

**Comment by artiomchi** [comment]
Hey @SimonLuckenuik,
Sorry for the long delay.

So, this is easy to fix to stop it from throwing an exception. I'll see what I can do to fix it asap.

Looking at your code - one issue is that this library won't run your code that updates your audit properties, since it generates it's own sql query.

Basically, any columns that don't have a property associated with them won't be updated. Even if they were on the model, unless you're updating their values in the upsert call, the sql generated won't be affected by any triggers you attach to the DB context (i.e. `AuditChangesFor`, I'm assuming you have it automated in some way)

My patch here would be to ignore these columns, since they don't have properties backing them in the entity classes.

**Comment by artiomchi** [comment]
I've had a new release that has the patch I described, version 2.1.0

It won't run your audit extension properties, but will at least stop it from throwing exceptions.

**Comment by artiomchi** [comment]
I'm closing this issue since there was no activity here for several months.
