### ISSUE TITLE
Can't process 100k entities at once time

### ISSUE THREAD

**Issue by msvprogs** [artiomchi/FlexLabs.Upsert#50]
When I try to upsert 100k items in the PostgreSQL database at once time:
```
var context = new TestContext();

context.TestEntities
	.UpsertRange(Enumerable.Range(1, 100000)
		.Select(x => new TestEntity {Id = x, SomeName = x.ToString()}))
	.Run();

context.SaveChanges();
```
the library throws the following exception:
```
System.Exception: A statement cannot have more than 65535 parameters
  at Npgsql.NpgsqlCommand.ProcessRawQuery(Boolean deriveParameters) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 784
  at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1157
  at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
  at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
  at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
  at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
  at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
  at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.Run[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Boolean noUpdate, Boolean useExpressionCompiler) in D:\Development\FlexLabs.Upsert\src\FlexLabs.EntityFrameworkCore.Upsert\Runners\RelationalUpsertCommandRunner.cs:line 234
  at FlexLabs.EntityFrameworkCore.Upsert.UpsertCommandBuilder`1.Run() in D:\Development\FlexLabs.Upsert\src\FlexLabs.EntityFrameworkCore.Upsert\UpsertCommandBuilder.cs:line 144
  at X.Program.Main(String[] args) in C:\Users\X\source\repos\X\Program.cs:line 14
```

Probably it's because PostgreSQL can't process INSERT statement with more than 65535 values.

**Comment by artiomchi** [comment]
Hi @msvprogs,

That's right.. In the [Usage](https://github.com/artiomchi/FlexLabs.Upsert/wiki/Usage) page, I've mentioned it here:

> In the same way, you can insert multiple entities in one call. Keep in mind that each database engine has a limit of how many parameters a query can be passed. Since each property will use up a variable, this should only be used with smaller datasets. For larger datasets an alternative approach may be needed.

Depending on the number of columns you're inserting, you can break down your dataset in smaller subsets, and process them in batches.

In MS SQL Server, larger datasets would be processed a lot faster when inserted using a tool like BCP. I'm not sure what would be a good option for Postgres

**Comment by PayteR** [comment]
@msvprogs i would rather suggest using transactions with `.Upsert()` and commit it after every 1000 row. 

Don't know much about PostgreSQL I'm using MySQL, but the result should be similar. Tried to compare `UpsertRange()` vs `Upsert()`+commit after every 1000 row and result was that `UpsertRange()` was faster, but it  was just about 5-10% but when you use `UpsertRange()` then there is big performance peak, by `Upsert()` there is no such a thing, it's very smooth all the time.

**Comment by montoner0** [comment]
@PayteR Unfortunately the way "commit 1000 rows" isn't universal. The size of a query is varying due to a different table structure and in my case even 200 rows is too much for some tables but fine for others. 
Until this issue will be solved this Upsert implementation is almost unusable. Run/RunAsync should split the query if it's too big as in EF Core's Save/SaveAsync.

**Comment by artiomchi** [comment]
As I mentioned previously - this library works well for a smaller number of inserts.. But it wouldn't be efficient for a larger set - in which case you should be using alternative solutions. I've discussed this at length in #63

**Comment by montoner0** [comment]
The main issue in my opinion is not inability to commit a lot of data but unpredictable amount. You can't guess at which moment it will be "too much" therefore can't make a solution for all cases.

**Comment by artiomchi** [comment]
@msvprogs @montoner0 So while I wasn't a big fan of this, you do make some good points, especially the unpredictable behaviour depending on the table width.

I did some research, and added default query parameter limits to the library, as well as added the code that will automatically split the query into multiple requests, if the parameter limit is reached.

You can get the latest CI build in the MyGet repo, and test it out for yourself.. Once I'm happy that it should be stable, and have finished some other cleanup, I'll push it to NuGet, but some external tests by you guys would help as well :)

**Comment by montoner0** [comment]
@artiomchi Sorry, I've moved to another solution currently but will try yours at some day.

**Comment by artiomchi** [comment]
Since this was deployed already, and there haven't been any issues raised regarding this, I'm closing this issue

**Comment by coconutbird** [comment]
> Since this was deployed already, and there haven't been any issues raised regarding this, I'm closing this issue

You should consider automatically splitting up queries so we can do 1 bulk operation

**Comment by baltermia** [comment]
I'm also interested in bulking functionality
