### ISSUE TITLE
Issue with 'hstore' type in PostgreSQL

### ISSUE THREAD

**Issue by dmitriifilonenko** [artiomchi/FlexLabs.Upsert#51]
In my PostgreSQL DB I have a table with a column of 'hstore' type. This column is projected to Dictionary type in C#. Here is how thic column described in code:

```
public class Product
{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long Id { get; set; }

        public Dictionary<string,string> Properties { get; set; }

        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }
}

public class DataContext : DbContext
{
        public DbSet<Product> Products { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.HasPostgresExtension("hstore");

            modelBuilder.Entity<Product>()
                .Property(p => p.Properties)
                .HasColumnType("hstore");
   
            ...
          }
}
```
Here is how I'm trying to upsert a record to this table:

```
serviceDataContext.Products.Upsert(new Product
                                    {
                                        Id = backendProduct.Id,
                                        Properties = backendProduct.Properties,
                                        Created = backendProduct.CreatedAt,
                                        Updated = backendProduct.UpdatedAt
                                    })
                                    .On(product => product.Id)
                                    .WhenMatched((productInDb, productNew) =>
                                        new Product
                                        {
                                            Properties = backendProduct.Properties,
                                            Updated = backendProduct.UpdatedAt
                                        })
                                    .Run();
```
At this stage I get an exception:

> Npgsql.NpgsqlException (0x80004005): The NpgsqlDbType 'Hstore' isn't present in your database. You may need to install an extension or upgrade to a newer version.
>    at Npgsql.TypeMapping.ConnectorTypeMapper.GetByNpgsqlDbType(NpgsqlDbType npgsqlDbType) in C:\projects\npgsql\src\Npgsql\TypeMapping\ConnectorTypeMapper.cs:line 106
>    at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper) in C:\projects\npgsql\src\Npgsql\NpgsqlParameter.cs:line 523
>    at Npgsql.NpgsqlCommand.ValidateParameters() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 796
>    at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1140
>    at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
>    at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
>    at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.Run[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Boolean noUpdate, Boolean useExpressionCompiler) in D:\Development\FlexLabs.Upsert\src\FlexLabs.EntityFrameworkCore.Upsert\Runners\RelationalUpsertCommandRunner.cs:line 234
>    at FlexLabs.EntityFrameworkCore.Upsert.UpsertCommandBuilder`1.Run() in D:\Development\FlexLabs.Upsert\src\FlexLabs.EntityFrameworkCore.Upsert\UpsertCommandBuilder.cs:line 144

As an experiment I replaced an upsert with standard 'Add' functionality from EF Core. Then everything works fine:
```
serviceDataContext.Products.Add(new Product
                {
                    Id = backendProduct.Id,
                    Properties = backendProduct.Properties,
                    Created = backendProduct.CreatedAt,
                    Updated = backendProduct.UpdatedAt
                });
```
So for me it looks likes the knowldege of data context about 'hstore' type is lost somewhere in between.

**Comment by dmitriifilonenko** [comment]
Sorry, my fault. The problem was in Npgsql.EntityFrameworkCore.PostgreSQL.(https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/292)
