### ISSUE TITLE
3.0 support

### ISSUE THREAD

**Issue by darkflame0** [artiomchi/FlexLabs.Upsert#58]
I used in 3.0 but got an exception

```
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior Microsoft.EntityFrameworkCore.Metadata.IProperty.get_AfterSaveBehavior()'.
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.<>c__14`1.<PrepareCommand>b__14_1(IProperty p)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.PrepareCommand[TEntity](IEntityType entityType, ICollection`1 entities, Expression`1 match, Expression`1 updater, Expression`1 updateCondition, Boolean noUpdate, Boolean useExpressionCompiler)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.RunAsync[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Expression`1 updateCondition, Boolean noUpdate, Boolean useExpressionCompiler, CancellationToken cancellationToken)
```

**Comment by APIWT** [comment]
Can you provide some more detail? Perhaps the code that you are trying to use?

**Comment by Nikolay-Simonov** [comment]
I also get this exception. EFCore 3.0 Preview 5.

```
await _dbContext.CartLines.UpsertRange(cartLines)
    .On(cl => new {cl.ProductId, cl.UserId})
    .WhenMatched((old, @new) => new CartLine
    {
        Quantity = @new.Quantity
    })
    .RunAsync();
```

**Comment by artiomchi** [comment]
Hi @darkflame0 , @Nikolay-Simonov 

I started checking the upgrade notes for EF Core 3.0, and there are a number of internal metadata changes that they've made which broke this library. I started trying to make a v3 branch, but I'm having some issues with some of their changes, besides just the metadata changes.

For the basic functionality, I've created proxy methods to simulate the ones added in EF Core 3, and I've just pushed the latest build with it to the CI server.  
Could you check if it's working for you with this latest update?

I'll be working on proper v3 support in the coming month.

**Comment by artiomchi** [comment]
Just so you know, making it work well with both EF Core 2.0 and 3.0 in the same assembly proved.. harder to manage, but it would also affect performance due to me having to use reflection.

So to avoid that, I'm moving the EF Core development to a new branch, with a separate build. I managed to run the tests in SQL Server and SQLite (with some caveats), and had to disable some in memory tests for the time being.

I don't have the tests running in MySQL and Postgres at the moment, but I'll see what I can do about them

Other than that, I can see the main functionality working well so far in EF Core 3.0

I've just pushed the new pre-release build to NuGet with this pre-release version: [3.0.0-netcore3-00140](https://www.nuget.org/packages/FlexLabs.EntityFrameworkCore.Upsert/3.0.0-netcore3-00140)

Please let me know if the new build works as expected for you

**Comment by artiomchi** [comment]
I'm closing this issue since there was no activity here for several months.

**Comment by faraxx** [comment]
this error exists in ef preview 6

**Comment by artiomchi** [comment]
It's not quite the same error, but you're right, EF 6 is bringing some breaking changes..  This should probably have been a new issue though.

I just pushed a pre-release build that has EF Core 6 support, so you should try it out :)
