### ISSUE TITLE
Exception generated on "only insert" on sql server

### ISSUE THREAD

**Issue by riccimatic** [artiomchi/FlexLabs.Upsert#84]
Hi,
 to understand the issue, i describe the scenario.

I have a queue that process some items with serial approach.
The items arrive to the routine from an external source. 
These items have an unique column (MessageId), different from primary key, used to prevent items duplication in database (contain the external source identifier).

The target is: add in table missing items, and do nothing if exist, all based on this unique column.

I work on app deployed on linux server that use .net core 3.1 and entity framework core 3.1.2 and store on sql server 2019 express.
The library used is: FlexLabs.EntityFrameworkCore.Upsert 3.1.0

Before using this library, the task was performed using 2 queries, the first that check if item exist, the second that insert missing item (context.ActiveDirectoryAccess.Add(item)).

Here the components.

The tables are:
<pre><code>
CREATE TABLE [dbo].[ActiveDirectoryAccessType](
	[Id] [int] NOT NULL,
	[Label] [char](25) NOT NULL,
 CONSTRAINT [PK_ActiveDirectoryAccessType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ActiveDirectoryAccessMethod](
	[Id] [int] NOT NULL,
	[Label] [char](10) NOT NULL,
 CONSTRAINT [PK_ActiveDirectoryAccessMethod] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ActiveDirectoryAccess](
	[Id] [uniqueidentifier] NOT NULL,
	[AccessTimestamp] [datetime] NOT NULL,
	[AccessPerformedBy] [nvarchar](255) NOT NULL,
	[AccessType] [int] NOT NULL,
	[DestinationHost] [nvarchar](255) NOT NULL,
	[SourceHost] [nvarchar](255) NOT NULL,
	[SourceIp] [nvarchar](50) NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[UpdatedOn] [datetime] NOT NULL,
	[AccessMethod] [int] NOT NULL,
	[AccessTimestampLocal] [datetime] NOT NULL,
	[MessageId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_ActiveDirectoryAccess] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ActiveDirectoryAccess] ADD  CONSTRAINT [DF__ActiveDir__Creat__59FA5E80]  DEFAULT ('2000-01-01 00:00:00.000') FOR [CreatedOn]
GO

ALTER TABLE [dbo].[ActiveDirectoryAccess] ADD  CONSTRAINT [DF__ActiveDir__Updat__5AEE82B9]  DEFAULT ('2000-01-01 00:00:00.000') FOR [UpdatedOn]
GO

ALTER TABLE [dbo].[ActiveDirectoryAccess] ADD  CONSTRAINT [DF__ActiveDir__Acces__04E4BC85]  DEFAULT ((0)) FOR [AccessMethod]
GO

ALTER TABLE [dbo].[ActiveDirectoryAccess] ADD  CONSTRAINT [DF__ActiveDir__Acces__08B54D69]  DEFAULT ('2000-01-01 00:00:00.000') FOR [AccessTimestampLocal]
GO

ALTER TABLE [dbo].[ActiveDirectoryAccess]  WITH CHECK ADD  CONSTRAINT [FK_ActiveDirectoryAccess_ActiveDirectoryAccessMethod] FOREIGN KEY([AccessMethod])
REFERENCES [dbo].[ActiveDirectoryAccessMethod] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ActiveDirectoryAccess] CHECK CONSTRAINT [FK_ActiveDirectoryAccess_ActiveDirectoryAccessMethod]
GO

ALTER TABLE [dbo].[ActiveDirectoryAccess]  WITH CHECK ADD  CONSTRAINT [FK_ActiveDirectoryAccess_ActiveDirectoryAccessType] FOREIGN KEY([AccessType])
REFERENCES [dbo].[ActiveDirectoryAccessType] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ActiveDirectoryAccess] CHECK CONSTRAINT [FK_ActiveDirectoryAccess_ActiveDirectoryAccessType]
GO
</code></pre>

the c# definitions (generated using Scaffold-DbContext) are:
<pre><code>
public partial class ActiveDirectoryAccessMethod
    {
        public ActiveDirectoryAccessMethod()
        {
            ActiveDirectoryAccess = new HashSet<ActiveDirectoryAccess>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(10)]
        public string Label { get; set; }

        [InverseProperty("AccessMethodNavigation")]
        public virtual ICollection<ActiveDirectoryAccess> ActiveDirectoryAccess { get; set; }
    }

public partial class ActiveDirectoryAccessType
    {
        public ActiveDirectoryAccessType()
        {
            ActiveDirectoryAccess = new HashSet<ActiveDirectoryAccess>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(25)]
        public string Label { get; set; }

        [InverseProperty("AccessTypeNavigation")]
        public virtual ICollection<ActiveDirectoryAccess> ActiveDirectoryAccess { get; set; }
    }

public partial class ActiveDirectoryAccess
    {
        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AccessTimestamp { get; set; }
        [Required]
        [StringLength(255)]
        public string AccessPerformedBy { get; set; }
        public int AccessType { get; set; }
        [Required]
        [StringLength(255)]
        public string DestinationHost { get; set; }
        [Required]
        [StringLength(255)]
        public string SourceHost { get; set; }
        [Required]
        [StringLength(50)]
        public string SourceIp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdatedOn { get; set; }
        public int AccessMethod { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AccessTimestampLocal { get; set; }
        public Guid MessageId { get; set; }

        [ForeignKey(nameof(AccessMethod))]
        [InverseProperty(nameof(ActiveDirectoryAccessMethod.ActiveDirectoryAccess))]
        public virtual ActiveDirectoryAccessMethod AccessMethodNavigation { get; set; }
        [ForeignKey(nameof(AccessType))]
        [InverseProperty(nameof(ActiveDirectoryAccessType.ActiveDirectoryAccess))]
        public virtual ActiveDirectoryAccessType AccessTypeNavigation { get; set; }
    }
</code></pre>

The procedure set the fields and try to upsert in table dbo.ActiveDirectoryAccess:
<pre><code>
ActiveDirectoryAccess item = new ActiveDirectoryAccess()
{
    Id = Guid.NewGuid(),
    CreatedOn = DateTime.UtcNow,
    UpdatedOn = DateTime.UtcNow,
    AccessTimestamp = ((SuccessfullyLogin)result.Result).TimestampUtc,
    AccessTimestampLocal = ((SuccessfullyLogin)result.Result).TimestampUtc.GetItalianTimeZoneDateTime(),
    AccessPerformedBy = ((SuccessfullyLogin)result.Result).Account.ToString(),
    AccessType = Common.DataObject.StructuredLogs.ActiveDirectoryAccess.AccessType.SuccessfullyLogin.GetValue(),
    DestinationHost = ((SuccessfullyLogin)result.Result).DestinationHost,
    SourceHost = ((SuccessfullyLogin)result.Result).SourceHost,
    SourceIp = ((SuccessfullyLogin)result.Result).SourceIp,
    AccessMethod = ((SuccessfullyLogin)result.Result).Method.GetValue(),
    MessageId = logSummary.MessageId
};

context.ActiveDirectoryAccess.Upsert(item).On(x => x.MessageId).NoUpdate().Run();

context.SaveChanges();

</code></pre>

Here a data sample:
<pre><code>
{
    "Id": "35eaa276-4e57-4488-b77e-0138e61c1c72",
    "AccessTimestamp": "2020-04-01T21:00:51.4324588Z",
    "AccessPerformedBy": "admin-service",
    "AccessType": 2,
    "DestinationHost": "VCDC03.xxx.locale",
    "SourceHost": "",
    "SourceIp": "",
    "CreatedOn": "2020-04-14T13:00:14.1499881Z",
    "UpdatedOn": "2020-04-14T13:00:14.1606314Z",
    "AccessMethod": 2,
    "AccessTimestampLocal": "2020-04-01T23:00:51.4324588",
    "MessageId": "b1cf1611-7461-11ea-8e32-000c29530a52",
    "AccessMethodNavigation": null,
    "AccessTypeNavigation": null
}
</code></pre>

On existing items in table, all work as expected, on missing item, generate this exception:
<pre><code>
Cannot insert the value NULL into column 'Id', table 'appdb.dbo.ActiveDirectoryAccess'; column does not allow nulls. UPDATE fails.The statement has been terminated.

at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.Run[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Expression`1 updateCondition, RunnerQueryOptions queryOptions)
   at FlexLabs.EntityFrameworkCore.Upsert.UpsertCommandBuilder`1.Run()
</code></pre>

Seems that the field 'Id' (primary key) is not recognized.

Any idea?

Thanks to all for support.

Stefano

**Comment by artiomchi** [comment]
Hi @riccimatic 

That's a strange one - from the looks of it, the code should work just fine - I even have this case covered in the unit tests in the `GuidKeyAutoGen` table.

What you could do is add this attribute to your Id property, to tell the framework (and the upsert library) that you'll be providing your own values, and they should not be auto-generated. This should fix the issue

```csharp
public partial class ActiveDirectoryAccess
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
    public Guid Id { get; set; }
}
```

Please let me know if this worked for you.

**Comment by artiomchi** [comment]
Closing due to inactivity for months. If this issue persists, please don't hesitate to re-open the issue or start a new one

**Comment by anonym-collaborator** [comment]
Thank you! The DatabaseGenerated(DatabaseGeneratedOption.None) attribute helped with this issue.

I also encountered the error: "Cannot insert the value NULL into column 'Id', table <tableName>; column does not allow nulls. UPDATE fails. The statement has been terminated."

This happens when the Id column is a Guid, and the database doesn't generate a value for it automatically 🙂
