### ISSUE TITLE
InMemory database throws exception in .NET5

### ISSUE THREAD

**Issue by Mike-E-angelo** [artiomchi/FlexLabs.Upsert#99]
Upgrading to .NET5 here and there seems to be an exception that I did not encounter with `.NETCore3.1`:

```
System.ArgumentException
must be reducible node
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile()
   at System.Linq.EnumerableQuery`1.GetEnumerator()
   at System.Linq.EnumerableQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.InMemoryUpsertCommandRunner.FindMatches[TEntity](IEntityType entityType, IEnumerable`1 entities, DbContext dbContext, Expression`1 matchExpression)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.InMemoryUpsertCommandRunner.RunCore[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Expression`1 updateCondition, RunnerQueryOptions queryOptions)
   at FlexLabs.EntityFrameworkCore.Upsert.Runners.InMemoryUpsertCommandRunner.Run[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Expression`1 updateCondition, RunnerQueryOptions queryOptions)
   at FlexLabs.EntityFrameworkCore.Upsert.UpsertCommandBuilder`1.Run()
```

Code that causes this:

```
dbContext.Set<Entity>().Upsert(entity).On(x => x.Name).Run();
```

where `Entity`:

```

public class Entity
{
	public Guid Id { get; set; }

	public string Name { get; set; } = default!;
}
```

There's actually a bit more code there but I am thinking it is not relevant due to this working in `.NETCore3.1`.  However, please do let me know if you require more to help diagnose this issue and I will do my best to see if I can get it to you. 👍

**Comment by valentasm1** [comment]
Any aprox deadline?

**Comment by APIWT** [comment]
@valentasm1 I would suggest making a pull request as this project has been very much so great about taking contributions in a timely manner.

**Comment by valentasm1** [comment]
I will give a shot to fix it locally, but i am for from having  enough knowleadge about ef core

**Comment by tinduong** [comment]
I got the same issue when trying to upgrade core 3.1 to Net 5.0. Any idea? work around?

**Comment by RomanGolovanov** [comment]
@tinduong you could try this workaround, it's work fine for our tests dataset size: 
[https://github.com/RomanGolovanov/FlexLabs.Upsert/commit/da1c62b1941480b76b5399fbf84d3d086205c0e3](url)

**Comment by artiomchi** [comment]
Seems like this is a regression in the expression compiler in the InMemory EF Core driver, which is unfortunate.

I was hoping to avoid something like @RomanGolovanov's solution, as it converts the whole DbSet into an in memory list, but I don't really see another alternative here.

I'm merging your commit into the project, as it seems to sort out this problem. Thanks for providing it here!

**Comment by tinduong** [comment]
@RomanGolovanov  Thank you for a quick response. I will try this out...
